title: Homayoun Mahmoudy # your name (or website title) here
logo: "/images/IMG_0442.JPG? raw=true " # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Seasoned Statistician with more than 20 years experience in
  <br><br>
  Marketing and Advertising Research and Modeling
  <br><br>
  <a href="https://www.linkedin.com/in/homayoun-baybourdy-82464114/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
